// Generated by agents/generate-rss-catalog.py from feeds.json. Do not edit.
var officialFeed = {
  "id": "omarchy",
  "name": "Omarchy",
  "description": "Official Omarchy announcements",
  "category": "official",
  "url": "https://omarchy.org/news/rss.xml"
}

var feeds = [
  {
    "id": "hacker-news",
    "name": "Hacker News",
    "description": "Developer and startup news",
    "category": "developer",
    "url": "https://news.ycombinator.com/rss"
  },
  {
    "id": "ars-technica",
    "name": "Ars Technica",
    "description": "Deep technology, science and security",
    "category": "technology",
    "url": "https://feeds.arstechnica.com/arstechnica/index"
  },
  {
    "id": "techcrunch",
    "name": "TechCrunch",
    "description": "Startups, business and AI",
    "category": "startup",
    "url": "https://techcrunch.com/feed/"
  },
  {
    "id": "the-verge",
    "name": "The Verge",
    "description": "Mainstream technology and platforms",
    "category": "technology",
    "url": "https://www.theverge.com/rss/index.xml"
  },
  {
    "id": "wired",
    "name": "WIRED",
    "description": "Technology, science, security and culture",
    "category": "technology",
    "url": "https://www.wired.com/feed/rss"
  },
  {
    "id": "phoronix",
    "name": "Phoronix",
    "description": "Linux kernel, hardware and performance",
    "category": "linux",
    "url": "https://www.phoronix.com/rss.php"
  },
  {
    "id": "its-foss",
    "name": "It's FOSS",
    "description": "Accessible Linux and open-source coverage",
    "category": "linux",
    "url": "https://itsfoss.com/rss/"
  },
  {
    "id": "openai-news",
    "name": "OpenAI News",
    "description": "Official OpenAI product and research news",
    "category": "ai",
    "url": "https://openai.com/news/rss.xml"
  },
  {
    "id": "hugging-face",
    "name": "Hugging Face",
    "description": "Open models, tooling and AI research",
    "category": "ai",
    "url": "https://huggingface.co/blog/feed.xml"
  },
  {
    "id": "mit-ai",
    "name": "MIT News: AI",
    "description": "Academic AI research and developments",
    "category": "ai",
    "url": "https://news.mit.edu/rss/topic/artificial-intelligence2"
  }
]

var techFeedIds = [
  "hacker-news",
  "ars-technica",
  "techcrunch",
  "the-verge",
  "wired",
  "phoronix",
  "its-foss",
  "openai-news",
  "hugging-face",
  "mit-ai"
]

if (typeof module !== "undefined") {
  module.exports = { officialFeed: officialFeed, feeds: feeds, techFeedIds: techFeedIds }
}
