"""Generate checked-in RSS UI metadata from the package-owned feed catalogue."""

import argparse
import json
import re
from pathlib import Path
from urllib.parse import urlparse

PLUGIN = Path(__file__).resolve().parents[1]
UI_FIELDS = ("id", "name", "description", "category", "url")


def load_catalog(path: Path) -> list[dict]:
    feeds = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(feeds, list) or not feeds:
        raise ValueError("catalogue must be a non-empty list")
    seen = set()
    fields = set(UI_FIELDS) | {"packs", "article_hosts", "article_path_prefix", "allow_external_articles"}
    for feed in feeds:
        if not isinstance(feed, dict) or set(feed) != fields:
            raise ValueError("each feed must declare exactly the catalogue fields, including URL policy")
        if any(not isinstance(feed[key], str) or not feed[key] for key in UI_FIELDS):
            raise ValueError("feed display fields must be non-empty strings")
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", feed["id"]) or feed["id"] in seen:
            raise ValueError("feed IDs must be unique lowercase slugs")
        seen.add(feed["id"])
        url = urlparse(feed["url"])
        if url.scheme != "https" or not url.hostname or url.username or url.password or url.fragment or url.port not in (None, 443):
            raise ValueError(f"{feed['id']}: invalid HTTPS feed URL")
        if not isinstance(feed["packs"], list) or any(pack != "tech" for pack in feed["packs"]) or len(feed["packs"]) > 1:
            raise ValueError(f"{feed['id']}: invalid pack membership")
        hosts = feed["article_hosts"]
        if not isinstance(hosts, list) or any(not isinstance(host, str) or not re.fullmatch(r"[a-z0-9]+(?:[.-][a-z0-9]+)*", host) for host in hosts):
            raise ValueError(f"{feed['id']}: invalid article hosts")
        if type(feed["allow_external_articles"]) is not bool or (not hosts and not feed["allow_external_articles"]):
            raise ValueError(f"{feed['id']}: declare article hosts or explicitly allow external articles")
        if not isinstance(feed["article_path_prefix"], str) or not feed["article_path_prefix"].startswith("/"):
            raise ValueError(f"{feed['id']}: article path prefix must start with /")
    if "omarchy" not in seen or next(feed for feed in feeds if feed["id"] == "omarchy")["packs"]:
        raise ValueError("the pinned Omarchy feed must exist outside optional packs")
    return feeds


def outputs(plugin: Path) -> dict[Path, str]:
    feeds = load_catalog(plugin / "feeds.json")
    official = next(feed for feed in feeds if feed["id"] == "omarchy")
    optional = [feed for feed in feeds if feed["id"] != "omarchy"]
    values = {
        "officialFeed": {key: official[key] for key in UI_FIELDS},
        "feeds": [{key: feed[key] for key in UI_FIELDS} for feed in optional],
        "techFeedIds": [feed["id"] for feed in feeds if "tech" in feed["packs"]],
    }
    javascript = "// Generated by agents/generate-rss-catalog.py from feeds.json. Do not edit.\n"
    for name, value in values.items():
        javascript += f"var {name} = " + json.dumps(value, ensure_ascii=True, indent=2) + "\n\n"
    javascript += 'if (typeof module !== "undefined") {\n  module.exports = { officialFeed: officialFeed, feeds: feeds, techFeedIds: techFeedIds }\n}\n'
    manifest = json.loads((plugin / "manifest.json").read_text(encoding="utf-8"))
    setting = next(entry for entry in manifest["barWidget"]["schema"] if entry["key"] == "enabledFeeds")
    setting["options"] = [{"value": feed["id"], "label": feed["name"], "description": feed["description"]} for feed in optional]
    return {
        plugin / "FeedCatalog.js": javascript,
        plugin / "manifest.json": json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on stale generated files without writing")
    args = parser.parse_args()
    stale = []
    for path, content in outputs(PLUGIN).items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.name)
        else:
            path.write_text(content, encoding="utf-8")
    if stale:
        print("Stale RSS metadata: " + ", ".join(stale) + ". Run python3 agents/generate-rss-catalog.py")
    return int(bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
